language: node_js
node_js:
  "8"
before_script:
  - npm install
script: npm run build
deploy:
  provider: surge
  project: ./build/
  domain: localhost
after_success:
  - npm run deploy
skip_cleanup: true
